/**
 * AttackData.js - Data-Driven Attack & Frame Data System
 * Defines startup, active, recovery, damage, knockback, and properties.
 */
window.NeonRumble = window.NeonRumble || {};

(function() {
  const Box = window.NeonRumble.Box;

  const AttackData = {
    // Standard Attacks
    LIGHT: {
      name: 'Light Attack',
      startup: 4,
      active: 4,
      recovery: 8,
      damage: 7,
      chipDamage: 1,
      knockback: { x: 3.5, y: 0 },
      hitstun: 15,
      blockstun: 9,
      freezeFrames: 4,
      meterGainAttacker: 6,
      meterGainDefender: 3,
      property: 'MID',
      level: 'LIGHT',
      hitbox: new Box(25, -55, 42, 25, 'hit')
    },
    HEAVY: {
      name: 'Heavy Attack',
      startup: 9,
      active: 6,
      recovery: 16,
      damage: 17,
      chipDamage: 3,
      knockback: { x: 7.5, y: -3.5 },
      hitstun: 26,
      blockstun: 16,
      freezeFrames: 8,
      meterGainAttacker: 14,
      meterGainDefender: 6,
      property: 'MID',
      level: 'HEAVY',
      hitbox: new Box(22, -65, 52, 38, 'hit')
    },
    KICK: {
      name: 'Thrust Kick',
      startup: 6,
      active: 5,
      recovery: 12,
      damage: 12,
      chipDamage: 2,
      knockback: { x: 5.5, y: -1.5 },
      hitstun: 20,
      blockstun: 12,
      freezeFrames: 6,
      meterGainAttacker: 10,
      meterGainDefender: 4,
      property: 'MID',
      level: 'MEDIUM',
      hitbox: new Box(26, -48, 48, 28, 'hit')
    },
    CROUCH_LIGHT: {
      name: 'Crouch Light',
      startup: 5,
      active: 4,
      recovery: 7,
      damage: 6,
      chipDamage: 1,
      knockback: { x: 2.8, y: 0 },
      hitstun: 14,
      blockstun: 8,
      freezeFrames: 4,
      meterGainAttacker: 5,
      meterGainDefender: 2,
      property: 'LOW',
      level: 'LIGHT',
      hitbox: new Box(20, -22, 45, 20, 'hit')
    },
    CROUCH_HEAVY: {
      name: 'Crouch Sweep',
      startup: 10,
      active: 5,
      recovery: 18,
      damage: 15,
      chipDamage: 3,
      knockback: { x: 6.0, y: -4.5 },
      hitstun: 28,
      blockstun: 15,
      freezeFrames: 8,
      meterGainAttacker: 12,
      meterGainDefender: 5,
      property: 'LOW',
      level: 'HEAVY',
      causesKnockdown: true,
      hitbox: new Box(18, -25, 58, 24, 'hit')
    },
    JUMP_LIGHT: {
      name: 'Jump Light',
      startup: 4,
      active: 6,
      recovery: 6,
      damage: 8,
      chipDamage: 1,
      knockback: { x: 3.5, y: 1.5 },
      hitstun: 16,
      blockstun: 10,
      freezeFrames: 5,
      meterGainAttacker: 7,
      meterGainDefender: 3,
      property: 'HIGH',
      level: 'LIGHT',
      hitbox: new Box(22, -45, 38, 30, 'hit')
    },
    JUMP_HEAVY: {
      name: 'Jump Heavy',
      startup: 8,
      active: 8,
      recovery: 10,
      damage: 18,
      chipDamage: 3,
      knockback: { x: 6.5, y: 3.0 },
      hitstun: 24,
      blockstun: 16,
      freezeFrames: 9,
      meterGainAttacker: 15,
      meterGainDefender: 6,
      property: 'HIGH',
      level: 'HEAVY',
      hitbox: new Box(20, -50, 48, 42, 'hit')
    },

    // Character Specific Specials
    ARDRA_SPECIAL: {
      name: 'Storm Gale Vortex',
      startup: 8,
      active: 16,
      recovery: 14,
      damage: 20,
      chipDamage: 4,
      knockback: { x: 8.5, y: -5.0 },
      hitstun: 30,
      blockstun: 16,
      freezeFrames: 7,
      meterCost: 25,
      meterGainAttacker: 10,
      meterGainDefender: 6,
      property: 'MID',
      level: 'SPECIAL',
      causesKnockdown: true,
      hitbox: new Box(15, -70, 75, 60, 'hit')
    },
    ARDRA_SUPER: {
      name: 'Long Tongue Lash (Bitchy Timeee!!!)',
      startup: 6,
      active: 36,
      recovery: 20,
      damage: 50,
      chipDamage: 10,
      knockback: { x: 12.0, y: -7.0 },
      hitstun: 55,
      blockstun: 25,
      freezeFrames: 14,
      meterCost: 100,
      property: 'MID',
      level: 'SUPER',
      causesKnockdown: true,
      hitbox: new Box(15, -75, 220, 65, 'hit')
    },

    REX_SPECIAL: {
      name: 'Mach Shockwave',
      startup: 12,
      active: 6,
      recovery: 14,
      damage: 16,
      chipDamage: 3,
      knockback: { x: 7.0, y: -3.0 },
      hitstun: 25,
      blockstun: 14,
      freezeFrames: 6,
      meterCost: 25,
      meterGainAttacker: 8,
      meterGainDefender: 4,
      property: 'MID',
      level: 'SPECIAL',
      spawnsProjectile: true,
      projectileType: 'REX_WAVE',
      hitbox: new Box(20, -45, 45, 35, 'hit')
    },
    REX_SUPER: {
      name: 'Meteor Buster',
      startup: 7,
      active: 24,
      recovery: 24,
      damage: 48,
      chipDamage: 9,
      knockback: { x: 14.0, y: -7.5 },
      hitstun: 55,
      blockstun: 25,
      freezeFrames: 14,
      meterCost: 100,
      property: 'MID',
      level: 'SUPER',
      causesKnockdown: true,
      hitbox: new Box(20, -60, 80, 55, 'hit')
    },

    VOLT_SPECIAL: {
      name: 'Plasma Arc',
      startup: 10,
      active: 6,
      recovery: 15,
      damage: 15,
      chipDamage: 3,
      knockback: { x: 6.0, y: -2.0 },
      hitstun: 24,
      blockstun: 13,
      freezeFrames: 5,
      meterCost: 25,
      meterGainAttacker: 8,
      meterGainDefender: 4,
      property: 'MID',
      level: 'SPECIAL',
      spawnsProjectile: true,
      projectileType: 'VOLT_ORB',
      hitbox: new Box(25, -50, 40, 35, 'hit')
    },
    VOLT_SUPER: {
      name: 'Thunder Overload',
      startup: 8,
      active: 26,
      recovery: 20,
      damage: 45,
      chipDamage: 8,
      knockback: { x: 6.0, y: -9.0 },
      hitstun: 50,
      blockstun: 25,
      freezeFrames: 12,
      meterCost: 100,
      property: 'MID',
      level: 'SUPER',
      causesKnockdown: true,
      spawnsLightningColumn: true,
      hitbox: new Box(15, -80, 90, 80, 'hit')
    },

    TITAN_SPECIAL: {
      name: 'Seismic Slam',
      startup: 16,
      active: 10,
      recovery: 20,
      damage: 22,
      chipDamage: 5,
      knockback: { x: 9.0, y: -6.0 },
      hitstun: 32,
      blockstun: 18,
      freezeFrames: 9,
      meterCost: 25,
      meterGainAttacker: 12,
      meterGainDefender: 6,
      property: 'MID',
      level: 'SPECIAL',
      causesKnockdown: true,
      hitbox: new Box(10, -50, 85, 50, 'hit')
    },
    TITAN_SUPER: {
      name: 'Tectonic Cataclysm',
      startup: 10,
      active: 30,
      recovery: 26,
      damage: 52,
      chipDamage: 10,
      knockback: { x: 10.0, y: -9.5 },
      hitstun: 60,
      blockstun: 28,
      freezeFrames: 14,
      meterCost: 100,
      property: 'MID',
      level: 'SUPER',
      causesKnockdown: true,
      hitbox: new Box(5, -75, 120, 75, 'hit')
    }
  };

  window.NeonRumble.AttackData = AttackData;
})();
